// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ4YCNqS7D1XWT4vPMO7r6RkzMyAHzVPk',
    appId: '1:224701946866:web:3c54a172f62c2ecfe3a96b',
    messagingSenderId: '224701946866',
    projectId: 'carrentalapp-8bd0a',
    authDomain: 'carrentalapp-8bd0a.firebaseapp.com',
    storageBucket: 'carrentalapp-8bd0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKQ4sPMFjgONCF0qtMSK5b37eMily7MME',
    appId: '1:224701946866:android:334a5d3a971c4b44e3a96b',
    messagingSenderId: '224701946866',
    projectId: 'carrentalapp-8bd0a',
    storageBucket: 'carrentalapp-8bd0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8OsBWCtYDR0n0RWc8skC7xWNOxtrOSyo',
    appId: '1:224701946866:ios:3f6a8e1eea3f1c7ce3a96b',
    messagingSenderId: '224701946866',
    projectId: 'carrentalapp-8bd0a',
    storageBucket: 'carrentalapp-8bd0a.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8OsBWCtYDR0n0RWc8skC7xWNOxtrOSyo',
    appId: '1:224701946866:ios:3f6a8e1eea3f1c7ce3a96b',
    messagingSenderId: '224701946866',
    projectId: 'carrentalapp-8bd0a',
    storageBucket: 'carrentalapp-8bd0a.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ4YCNqS7D1XWT4vPMO7r6RkzMyAHzVPk',
    appId: '1:224701946866:web:238b8119e219bec3e3a96b',
    messagingSenderId: '224701946866',
    projectId: 'carrentalapp-8bd0a',
    authDomain: 'carrentalapp-8bd0a.firebaseapp.com',
    storageBucket: 'carrentalapp-8bd0a.firebasestorage.app',
  );

}